### PR TITLE
Add support for Jenkins Pipeline

### PR DESCRIPTION
**Pull request by ansoni**
Re-factored to support the Pipeline plugin.  this addresses #36 

Had to update the Jenkins libraries and implement SimpleBuildStep.  All tests still passed.

README updated for how to use.

### CODE REVIEW

**Comment by hellvinz** [comment]
@ansoni I got a couple of warning that seems to prevent the `mvn install`:
```
[INFO] --- findbugs-maven-plugin:3.0.3:check (findbugs) @ codedeploy ---
[INFO] BugInstance size is 8
[INFO] Error size is 0
[INFO] Total bugs: 8
[INFO] Found reliance on default encoding in com.amazonaws.codedeploy.AWSClients.createTestFile(): new java.io.OutputStreamWriter(OutputStream) [com.amazonaws.codedeploy.AWSClients] At AWSClients.java:[line 132] DM_DEFAULT_ENCODING
[INFO] Alimentation à perte d'une variable locale dans la méthode com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(Run, FilePath, Launcher, TaskListener) [com.amazonaws.codedeploy.AWSCodeDeployPublisher] At AWSCodeDeployPublisher.java:[line 232] DLS_DEAD_LOCAL_STORE
[INFO] Found reliance on default encoding in com.amazonaws.codedeploy.AWSCodeDeployPublisher.zipAndUpload(AWSClients, String, FilePath): new java.io.FileReader(File) [com.amazonaws.codedeploy.AWSCodeDeployPublisher] At AWSCodeDeployPublisher.java:[line 299] DM_DEFAULT_ENCODING
[INFO] com.amazonaws.codedeploy.AWSCodeDeployPublisher.AVAILABLE_REGIONS devrait être package protected [com.amazonaws.codedeploy.AWSCodeDeployPublisher] At AWSCodeDeployPublisher.java:[line 80] MS_PKGPROTECT
[INFO] com.amazonaws.codedeploy.AWSCodeDeployPublisher.zipAndUpload(AWSClients, String, FilePath) may fail to clean up java.io.OutputStream [com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher, com.amazonaws.codedeploy.AWSCodeDeployPublisher] Obligation to clean up resource created at AWSCodeDeployPublisher.java:[line 346] is not dischargedPath continues at AWSCodeDeployPublisher.java:[line 351]Path continues at AWSCodeDeployPublisher.java:[line 352]Path continues at AWSCodeDeployPublisher.java:[line 361]Path continues at AWSCodeDeployPublisher.java:[line 362]Path continues at AWSCodeDeployPublisher.java:[line 364]Path continues at AWSCodeDeployPublisher.java:[line 365]Path continues at AWSCodeDeployPublisher.java:[line 366]Path continues at AWSCodeDeployPublisher.java:[line 367]Path continues at AWSCodeDeployPublisher.java:[line 368]Path continues at AWSCodeDeployPublisher.java:[line 370]Path continues at AWSCodeDeployPublisher.java:[line 371]Path continues at AWSCodeDeployPublisher.java:[line 372]Path continues at AWSCodeDeployPublisher.java:[line 374]Path continues at AWSCodeDeployPublisher.java:[line 376] OBL_UNSATISFIED_OBLIGATION
[INFO] Exceptional return value of java.io.File.createNewFile() ignored in com.amazonaws.codedeploy.AWSCodeDeployPublisher.zipAndUpload(AWSClients, String, FilePath) [com.amazonaws.codedeploy.AWSCodeDeployPublisher] At AWSCodeDeployPublisher.java:[line 312] RV_RETURN_VALUE_IGNORED_BAD_PRACTICE
[INFO] Exceptional return value of java.io.File.delete() ignored in com.amazonaws.codedeploy.AWSCodeDeployPublisher.zipAndUpload(AWSClients, String, FilePath) [com.amazonaws.codedeploy.AWSCodeDeployPublisher] At AWSCodeDeployPublisher.java:[line 376] RV_RETURN_VALUE_IGNORED_BAD_PRACTICE
[INFO] Boxing/unboxing to parse a primitive com.amazonaws.codedeploy.AWSCodeDeployPublisher$DescriptorImpl.configure(StaplerRequest, JSONObject) [com.amazonaws.codedeploy.AWSCodeDeployPublisher$DescriptorImpl] At AWSCodeDeployPublisher.java:[line 531] DM_BOXED_PRIMITIVE_FOR_PARSING
[INFO] 
```

**Comment by davividal** [comment]
I can't get neither `mvn` nor `mvn install` to work:

```
$ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building AWS CodeDeploy Plugin for Jenkins 1.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-hpi-plugin:1.106:validate (default-validate) @ codedeploy ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-maven) @ codedeploy ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:display-info (display-info) @ codedeploy ---
[INFO] Maven Version: 3.3.3
[INFO] JDK Version: 1.8.0_92 normalized as: 1.8.0-92
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 4.5.7-202.fc23.x86_64
[INFO] 
[INFO] --- maven-localizer-plugin:1.14:generate (default) @ codedeploy ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ codedeploy ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5:compile (default-compile) @ codedeploy ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- access-modifier-checker:1.7:enforce (default-enforce) @ codedeploy ---
[INFO] 
[INFO] --- maven-hpi-plugin:1.106:insert-test (default-insert-test) @ codedeploy ---
[INFO] 
[INFO] --- gmaven-plugin:1.5-jenkins-1:generateTestStubs (test-in-groovy) @ codedeploy ---
[INFO] No sources found for Java stub generation
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ codedeploy ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/davi.vidal/Documentos/projects/jenkins/aws-codedeploy-plugin/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5:testCompile (default-testCompile) @ codedeploy ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-hpi-plugin:1.106:test-hpl (default-test-hpl) @ codedeploy ---
[INFO] Generating /home/davi.vidal/Documentos/projects/jenkins/aws-codedeploy-plugin/target/test-classes/the.hpl
[INFO] 
[INFO] --- maven-hpi-plugin:1.106:resolve-test-dependencies (default-resolve-test-dependencies) @ codedeploy ---
[INFO] 
[INFO] --- gmaven-plugin:1.5-jenkins-1:testCompile (test-in-groovy) @ codedeploy ---
[INFO] No sources found to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ codedeploy ---
[INFO] Surefire report directory: /home/davi.vidal/Documentos/projects/jenkins/aws-codedeploy-plugin/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running InjectedTest
Running com.amazonaws.codedeploy.CodeDeployTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.767 sec <<< FAILURE! - in com.amazonaws.codedeploy.CodeDeployTest
testConfig(com.amazonaws.codedeploy.CodeDeployTest)  Time elapsed: 9.614 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.entrySet(OrderRetainingMap.java:77)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.putAll(HashMap.java:784)
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.<init>(OrderRetainingMap.java:36)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:135)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldsFor(FieldDictionary.java:76)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:127)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:149)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:108)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:898)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:887)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:860)
	at hudson.XmlFile.write(XmlFile.java:178)
	at jenkins.model.Jenkins.save(Jenkins.java:2672)
	at jenkins.model.Jenkins.setNoUsageStatistics(Jenkins.java:985)
	at org.jvnet.hudson.test.HudsonTestCase.setUp(HudsonTestCase.java:323)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at org.jvnet.hudson.test.HudsonTestCase.runBare(HudsonTestCase.java:293)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 10.899 sec <<< FAILURE! - in InjectedTest
org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite(org.jvnet.hudson.test.junit.FailedTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.entrySet(OrderRetainingMap.java:77)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.putAll(HashMap.java:784)
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.<init>(OrderRetainingMap.java:36)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:135)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldsFor(FieldDictionary.java:76)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:127)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:149)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:108)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:898)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:887)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:860)
	at hudson.XmlFile.write(XmlFile.java:178)
	at jenkins.model.Jenkins.save(Jenkins.java:2672)
	at jenkins.model.Jenkins.setNoUsageStatistics(Jenkins.java:985)
	at org.jvnet.hudson.test.HudsonTestCase.setUp(HudsonTestCase.java:323)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.setUp(JellyTestSuiteBuilder.java:133)
	at org.jvnet.hudson.test.junit.GroupedTest.run(GroupedTest.java:49)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

testCliSanity(org.jvnet.hudson.test.PluginAutomaticTestBuilder$CliSanityTest)  Time elapsed: 0.021 sec  <<< ERROR!
java.lang.IllegalStateException: second instance
	at jenkins.model.Jenkins.<init>(Jenkins.java:755)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at org.jvnet.hudson.test.HudsonTestCase.newHudson(HudsonTestCase.java:474)
	at org.jvnet.hudson.test.HudsonTestCase.setUp(HudsonTestCase.java:315)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at org.jvnet.hudson.test.HudsonTestCase.runBare(HudsonTestCase.java:293)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  CodeDeployTest>HudsonTestCase.runBare:293->HudsonTestCase.setUp:323 » ArrayIndexOutOfBounds
  FailedTest.org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite » ArrayIndexOutOfBounds
  PluginAutomaticTestBuilder$CliSanityTest>HudsonTestCase.runBare:293->HudsonTestCase.setUp:315->HudsonTestCase.newHudson:474 » IllegalState

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.087 s
[INFO] Finished at: 2016-07-28T17:13:42-03:00
[INFO] Final Memory: 27M/492M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project codedeploy: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/davi.vidal/Documentos/projects/jenkins/aws-codedeploy-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by raphaelquati** [comment]
It's not making the build result in failed deploy.
You need to set:

```
		if (!success) {
			build.setResult(Result.FAILURE);
		}
```

**Comment by jonathanhle** [comment]
+1  Any updates on getting this plugin Jenkins Pipeline / Jenkinsfile compatible?

**Comment by juziel** [comment]
+1

**Comment by francispereira** [comment]
+1

**Comment by nagaharayuuki** [comment]
+1

**Comment by Jmcfar** [comment]
Hi,

We merged pipeline support into the plugin under the newer PR: https://github.com/awslabs/aws-codedeploy-plugin/pull/72

Closing this out.

**Pull request closed without merging**
