### PR TITLE
aws sdk version upgraded to include new regions.

### PR DESCRIPTION
**Pull request by tridib**
To fix following issue.
https://github.com/awslabs/aws-codedeploy-plugin/issues/66

### CODE REVIEW

**Comment by shylaharild** [comment]
Jenkins Error when trying to use Code Deploy Plugin

```
ERROR: Step ‘Deploy an application to AWS CodeDeploy’ aborted due to exception: 
java.lang.NoSuchMethodError: com.amazonaws.services.codedeploy.AmazonCodeDeployClient.registerApplicationRevision(Lcom/amazonaws/services/codedeploy/model/RegisterApplicationRevisionRequest;)V
	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.registerRevision(AWSCodeDeployPublisher.java:388)
	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:226)
	at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by AnimaMundi** [comment]
Also receiving the following error,
please fix I'm completely blocked by this!

```
16:09:03 java.lang.NoSuchMethodError: com.amazonaws.services.codedeploy.AmazonCodeDeployClient.registerApplicationRevision(Lcom/amazonaws/services/codedeploy/model/RegisterApplicationRevisionRequest;)V
16:09:03 	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.registerRevision(AWSCodeDeployPublisher.java:388)
16:09:03 	at com.amazonaws.codedeploy.AWSCodeDeployPublisher.perform(AWSCodeDeployPublisher.java:226)
16:09:03 	at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
16:09:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
16:09:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
16:09:03 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
16:09:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
16:09:03 	at hudson.model.Run.execute(Run.java:1745)
16:09:03 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:09:03 	at hudson.model.ResourceController.execute(ResourceController.java:98)
16:09:03 	at hudson.model.Executor.run(Executor.java:404)
16:09:03 Finished: FAILURE
```

**Comment by martinbianco** [comment]
I have downgraded the Amazon Web Services SDK jenkins Plugin in order to resume my codedeploy capabilities.

would be great if fix can be released

**Comment by AnimaMundi** [comment]
@martinbianco can you please tell me how you done this? I only have an option to revert to an older installation if I had the previous version installed, but this problem is on a fresh Jenkins installation. What version did you downgrade to?

**Comment by tridib** [comment]
I wonder why this pull request is not yet merged. I am blocked and unable to use Jenkins to deploy on Mumbai data center.

**Comment by ibuys** [comment]
I ran into this issue just today. Any reason not to merge?

**Comment by westside** [comment]
I just built hpi file by changing the aws sdk version to 1.11.37, and works fine.

If somesone want to use it, u can download file from the link below.
https://drive.google.com/file/d/0B-yniu1Pmq_XWGdxUjRycWxXcDg/view?usp=sharing

You can install hpi file as below. 
http://stackoverflow.com/questions/14950408/how-to-install-a-plugin-in-jenkins-manually

thank you.

**Comment by Technowise** [comment]
@westside You just saved me from a lot of hassle. Thanks! But can someone please make this change to the repo and make a release so that it is fixed for everyone?

**Comment by jhuckabee** [comment]
Any update on a release with this fix?

**Comment by okobafox** [comment]
@westside Good Stuff Sir

**Comment by briannosaurus** [comment]
@westside i installed your hpi but it is still failing. even making my own hpi with different version in the pom doesn't fix this. How did you get it to work?

**Comment by vaniparidhyani** [comment]
@westside Thank you!

**Comment by pdehlke** [comment]
What's going on with this? Seems like a complete no-brainer merge; what am I missing?

**Comment by damianxd** [comment]
Can anyone please merge this crap? My setup is completely broken because of this

**Comment by derekbelrose** [comment]
It's been over a month, can someone please merge this PR?

**Comment by gdeblina** [comment]
Sorry for letting this sit for so long. We will take a look into this and get back soon.

**Comment by mvanbaak** [comment]
Any idea when 'soon' is?

**Comment by feverLu** [comment]
We've updated the jenkinsci repo, and once you update the CodeDeploy Jenkins plugin, you should be able to deploy in the new region: https://github.com/jenkinsci/aws-codedeploy-plugin/commit/d3a99b2cce02ba92a5586a200a6f535d563d61f4

**Pull request closed without merging**
